"""sync.py — commit (and optionally push) the artifacts a run rewrites.

`python -m src.run` rewrites TRACKED files — `build_data/*.json` and the
generated `APPENDIX.md`. Without this step they accumulate as uncommitted
working-tree edits, which is harmless day to day but collides the moment a
branch that also touches `build_data/` is merged.

Enable per-run with `--commit`, or standing on this machine with
`AUTO_COMMIT_ARTIFACTS=1` in infra/config.env (`$AUTO_COMMIT_ARTIFACTS` wins) —
the same override order as AGENT_BUNDLE_DIR.

Deliberate constraints, because this runs unattended:
  * Stages ONLY build_data/ and APPENDIX.md — never `git add -A`, so
    in-progress source edits are never swept into a data commit.
  * Nothing staged → no commit, no push, no noise.
  * Push only when the branch has an upstream, and only as a fast-forward:
    no force, no `--no-verify`, no upstream created for you. A rejected push
    leaves the commit sitting locally, which is the recoverable outcome.
  * `GIT_TERMINAL_PROMPT=0` plus timeouts on every call, so a credential
    prompt or a hung network can't stall the daily run indefinitely.
  * Every failure is soft: run.py calls this through `_safe`, and the deploy
    reads local files, so a sync failure never blocks shipping.
"""
from __future__ import annotations

import os
import subprocess
from datetime import date

from . import config, store

# Exactly the tracked outputs of a run. Keep this list tight — anything added
# here gets committed unattended.
ARTIFACT_PATHS = ("build_data", "APPENDIX.md")

_TIMEOUT_LOCAL = 30    # add/commit/rev-parse — local, should be instant
_TIMEOUT_PUSH = 120    # push — network


def _git(*args, timeout=_TIMEOUT_LOCAL) -> subprocess.CompletedProcess:
    """Run one git command in the repo root, non-interactive."""
    env = {**os.environ, "GIT_TERMINAL_PROMPT": "0", "GIT_OPTIONAL_LOCKS": "0"}
    return subprocess.run(
        ["git", *args], cwd=store.BASE, env=env, timeout=timeout,
        capture_output=True, text=True,
    )


def enabled() -> bool:
    """$AUTO_COMMIT_ARTIFACTS wins, then infra/config.env, else off."""
    val = os.environ.get("AUTO_COMMIT_ARTIFACTS")
    if val is None:
        val = config._load_env_config().get("AUTO_COMMIT_ARTIFACTS")
    return str(val).strip().lower() in {"1", "true", "yes", "on"}


def commit_and_push(push: bool = True) -> dict:
    """Commit the run's artifacts; push if the branch tracks an upstream.

    Returns a dict describing what happened (for the console + run_log). Raises
    only on genuinely unexpected conditions — run.py wraps this in _safe.
    """
    if not _git("rev-parse", "--git-dir").returncode == 0:
        return {"skipped": "not a git repository"}

    branch = _git("rev-parse", "--abbrev-ref", "HEAD").stdout.strip()

    add = _git("add", "--", *ARTIFACT_PATHS)
    if add.returncode != 0:
        return {"skipped": f"git add failed: {add.stderr.strip()[:120]}"}

    # --cached: only what we just staged, so unrelated dirty files are ignored.
    staged = _git("diff", "--cached", "--name-only", "--", *ARTIFACT_PATHS).stdout.split()
    out = {"branch": branch, "committed": False}

    if staged:
        msg = (f"Daily artifact refresh {date.today().isoformat()}\n\n"
               f"Regenerated by `python -m src.run` — {len(staged)} artifact file(s).\n"
               f"Data only; no methodology or source change.\n")
        commit = _git("commit", "-m", msg)
        if commit.returncode != 0:
            return {"skipped": f"git commit failed: {commit.stderr.strip()[:120]}"}
        out.update(committed=True, files=len(staged),
                   sha=_git("rev-parse", "--short", "HEAD").stdout.strip())
    else:
        out["reason"] = "artifacts unchanged"

    # Push is deliberately INDEPENDENT of whether we just committed: an earlier
    # run (or hand commit) can leave the branch ahead, and letting unpushed
    # commits accumulate is the same pile-up problem in a different place.
    if not push:
        out["push_reason"] = "push disabled"
        return out
    # No upstream → don't invent one; a local commit is the safe resting state.
    if _git("rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}").returncode != 0:
        out["push_reason"] = f"branch '{branch}' has no upstream"
        return out
    ahead = _git("rev-list", "--count", "@{u}..HEAD").stdout.strip()
    if ahead in ("", "0"):
        out["push_reason"] = "already up to date with upstream"
        return out

    p = _git("push", timeout=_TIMEOUT_PUSH)
    out["ahead"] = ahead
    out["pushed"] = p.returncode == 0
    if not out["pushed"]:
        # Most often a non-fast-forward (remote moved) or expired credentials.
        # Leave it local and say so; never force.
        out["push_reason"] = (p.stderr.strip() or p.stdout.strip() or "unknown")[:200]
    return out


def describe(res: dict | None) -> str:
    """One console line summarising the result."""
    if not res:
        return "Artifact sync: failed (see run_log.jsonl)"
    if "skipped" in res:
        return f"Artifact sync: skipped ({res['skipped']})"
    if res.get("committed"):
        head = f"committed {res['sha']} ({res['files']} files) on {res['branch']}"
    else:
        head = f"nothing to commit ({res.get('reason')}) on {res['branch']}"
    if res.get("pushed"):
        return f"Artifact sync: {head}; pushed {res.get('ahead')} commit(s)"
    return f"Artifact sync: {head}; not pushed — {res.get('push_reason')}"
